<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.peluware</groupId>
        <artifactId>freddy-cruder</artifactId>
        <version>3.1.0</version>
    </parent>

    <artifactId>freddy-cruder-spring-data-mongodb</artifactId>
    <name>Freddy Cruder Spring Data MongoDB</name>
    <description>Mongo integration for Freddy Cruder Spring Data module.</description>

    <properties>
        <org.springframework.boot.version>4.1.0</org.springframework.boot.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.peluware</groupId>
            <artifactId>freddy-cruder-spring-data</artifactId>
        </dependency>
        <dependency>
            <groupId>com.peluware</groupId>
            <artifactId>freddy-cruder-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-mongodb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.peluware</groupId>
            <artifactId>omni-search-mongodb</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${org.springframework.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>